name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run deploy script
        run: |
          ls -la
          chmod +x ./scripts/deploy-development.sh
          ./scripts/deploy-development.sh
