name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        run: |
          chmod +x ./scripts/deploy-development.sh
          ./scripts/deploy-development.sh
