name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Operations
        run: |
<<<<<<< HEAD
          git pull origin main
          git fetch --tags --force
  build :
=======
<<<<<<< Updated upstream
          chmod +x ./scripts/deploy-development.sh
          ./scripts/deploy-development.sh
=======
          cd ./
          git pull origin main
          git fetch --tags --force
  build :
    needs: deploy
>>>>>>> beaucoupdetaf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
<<<<<<< HEAD
=======
>>>>>>> Stashed changes
>>>>>>> beaucoupdetaf
